api_version = "2025-07"
uid = "1df01158-a666-d961-c1b6-f40ee1967450560f78de"

[[extensions]]
name = "Description Layouts"
handle = "description-layouts"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/BlockExtension.tsx"
  target = "admin.product-details.block.render"
