# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "706652ab86a2ead73ca0e780fe466246"
name = "Product Candy"
application_url = "https://productcandy.app/app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://productcandy.app/api/auth/callback" ]

[webhooks]
api_version = "2026-04"
