api_version = "2026-01"

[[extensions]]
name = "Image Resize & Crop"
handle = "image-tools"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/ActionExtension.tsx"
  target = "admin.product-details.action.render"
