api_version = "2025-07"
uid = "7e420071-0870-925e-5354-61199231aea4a8a18b4a"

[[extensions]]
name = "Image Resize & Crop"
handle = "image-tools"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/ActionExtension.tsx"
  target = "admin.product-details.action.render"
