api_version = "2025-07"
uid = "2383a6ff-cacc-01d2-deb8-b16fad6a2e75aef9d004"

[[extensions]]
name = "Pre-Made Description Layout Examples"
handle = "description-block"
type = "ui_extension"

  [extensions.icon]
  source = "./assets/icon.svg"

  [[extensions.targeting]]
  module = "./src/BlockExtension.tsx"
  target = "admin.product-details.block.render"
